import combinatorial_aspects_simplicial_complexes_foundation_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace combinatorial_aspects_simplicial_complexes_foundation_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end combinatorial_aspects_simplicial_complexes_foundation_canonical_lane_mathlib
end HautevilleHouse
